---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-frontend
  namespace: quote-app
  labels:
    app: quote-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-frontend
  template:
    metadata:
      labels:
        app: quote-frontend
    spec:
      containers:
        - name: frontend
          image: 040929397520.dkr.ecr.eu-west-2.amazonaws.com/quote-frontend:v05
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          imagePullPolicy: Always
---